### ISSUE TITLE
Calling Deprecated version of Ads API

### ISSUE THREAD

**Issue by jstraj** [facebook/facebook-java-ads-sdk#136]
Exception in thread "main" com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.12.","type":"OAuthException","code":2635,"fbtrace_id":"E+8hjKFIiTP"}}
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:226)
	at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:47)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendGet(APIRequest.java:356)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:334)
	at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:160)
	at com.facebook.ads.sdk.AdAccount$APIRequestGetInsights.execute(AdAccount.java:8220)
	at com.facebook.ads.sdk.AdAccount$APIRequestGetInsights.execute(AdAccount.java:8215)
	at facebook.Test.main(Test.java:25)}

My Code which I downloaded from Facebook:

```
APIContext context = new APIContext(access_token, app_secret).enableDebug(true);

        AdAccount adAccount = new AdAccount(ad_account_id, context);
                List<AdsInsights> adsInsights = adAccount.getInsights()
                                                .setLevel(AdsInsights.EnumLevel.VALUE_ADSET)
                                                .setFiltering("[]").setTimeIncrement("1")
                                                //.setBreakdowns(List<AdsInsights.EnumBreakdowns>.VALUE_["DAYS_1"])
                                                .setTimeRange("{\"since\":\"2018-02-01\",\"until\":\"2018-02-08\"}")
                                                .requestField("spend")
                                                .execute();
        for(AdsInsights adsInsights1: adsInsights) {
            System.out.println(adsInsights1.getFieldSpend());
        }
```

**Comment by guxufb** [comment]
you app should be created after v2.12 release.  If you are using the source code version of Java SDK, making changes to the following line is the quickest way.  
https://github.com/facebook/facebook-java-ads-sdk/blob/master/src/main/java/com/facebook/ads/sdk/APIConfig.java#L27
