### ISSUE TITLE
Conversion tracking 

### ISSUE THREAD

**Issue by markotron** [facebook/facebook-java-ads-sdk#35]
Hi, 

I'm trying to create an ad with all the Tracking settings in place. By all the tracking settings I mean pixel ID and URL parameters. 

I tryed with something like this: 

```Java
final ConversionActionQuery caq = new ConversionActionQuery();
        caq.setFieldFbPixel(Arrays.asList("621916377890091"));

        //formatter:off
        final Ad ad = account.createAd()
                        .setName("Java SDK Test ad")
                        .setAdsetId(Long.parseLong(adSet.getId()))
                        .setCreative(creative)
                        .setStatus("PAUSED")
                        .setBidAmount(100L)
                        .setRedownload(true)
                        .setTrackingSpecs(Arrays.asList(caq))
                        .execute();
        //formatter:on
```

but I get the StackOverflow exception

```
Caused by: java.lang.StackOverflowError: null
	at java.lang.Class.isPrimitive(Native Method) ~[na:1.8.0_65]
	at com.google.gson.internal.$Gson$Types.checkNotPrimitive($Gson$Types.java:432) ~[gson-2.3.1.jar:na]
	at com.google.gson.internal.$Gson$Types.access$000($Gson$Types.java:43) ~[gson-2.3.1.jar:na]
	at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:542) ~[gson-2.3.1.jar:na]
	at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:109) ~[gson-2.3.1.jar:na]
	at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:551) ~[gson-2.3.1.jar:na]
	at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:109) ~[gson-2.3.1.jar:na]
	at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:544) ~[gson-2.3.1.jar:na]
	at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:109) ~[gson-2.3.1.jar:na]
```

Any tips on how to make it work with the current SDK? 

Thanks!

**Comment by JiamingFB** [comment]
Hi markotron,

I can repro this issue and I'll work on it.

As a temporary workaround, you can pass a string to setTrackingSpecs(). You'll need to construct the json string based on the tracking spec.

**Comment by JiamingFB** [comment]
This is fixed in latest commit.
