### ISSUE TITLE
AdAccount.fetch() throws FailedRequestException

### ISSUE THREAD

**Issue by evgeniy-tg** [facebook/facebook-java-ads-sdk#41]
Hello,

My application receives FailedRequestException exception, when it tries to AdAccount.fetch() 
 
Exception: com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#100) Tried accessing nonexisting field (last_used_time) on node type (AdAccount)","type":"OAuthException","code":100,"fbtrace_id":"GHeibz8E4TY"}}
        at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:223)
        at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:44)
        at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendGet(APIRequest.java:344)
        at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:322)
        at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:157)
        at com.facebook.ads.sdk.AdAccount$APIRequestGet.execute(AdAccount.java:12225)
        at com.facebook.ads.sdk.AdAccount$APIRequestGet.execute(AdAccount.java:12220)
        at com.facebook.ads.sdk.AdAccount.fetchById(AdAccount.java:187)
        at com.facebook.ads.sdk.AdAccount.fetch(AdAccount.java:173)

It seems that facebook changed schema,  and now they are not returning 'last_used_time' field
java SDK should be changed accordingly.

Thanks,

**Comment by guxuoss** [comment]
Thanks for reporting the Ads API SDK bug! The issue you are reporting is not an Ads API SDK bug.  We would recommend to report this type of bugs through Facebook bug tool.  You will get better support on this type of issues.  Please refer to https://www.facebook.com/help/326603310765065 for Facebook bug tool.   

I will keep this issue open and post back while we get updates from the API side.

**Comment by guxuoss** [comment]
Please avoid using this field as it will be deprecated sooner or later.

**Comment by patelm5** [comment]
On what basis is this not a Ads SDK bug ? The SDK tries to request fields ( both last_used_time and owner_business ) on fetch() which are not listed in the Ads API ( they were removed I guess ). 

Surely this is just a case of updating the codegen tool to remove the same fields ?

**Comment by guxuoss** [comment]
Please wait for the changes on the API side.  Removing fields should not happen without bumping up the version.  We are still working on it and please be patient.
