### ISSUE TITLE
Error during campaign creation (#2) Service temporarily unavailable

### ISSUE THREAD

**Issue by alexeigit** [facebook/facebook-java-ads-sdk#81]
Hi,

I am trying to create a campaign like in you documentation, but i have an error
SDK version 0.4.0

```
com.facebook.ads.sdk.APIException$FailedRequestException: {"error":{"message":"(#2) Service temporarily unavailable","type":"OAuthException","is_transient":true,"code":2,"fbtrace_id":"GOSXBKzhrIb"}}
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:226)
	at com.facebook.ads.sdk.APIRequest.access$100(APIRequest.java:47)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.sendPost(APIRequest.java:409)
	at com.facebook.ads.sdk.APIRequest$DefaultRequestExecutor.execute(APIRequest.java:335)
	at com.facebook.ads.sdk.APIRequest.executeInternal(APIRequest.java:160)
	at com.facebook.ads.sdk.AdAccount$APIRequestCreateCampaign.execute(AdAccount.java:6882)
	at com.facebook.ads.sdk.AdAccount$APIRequestCreateCampaign.execute(AdAccount.java:6877)
	at com.ads.QuickStartExample.main(QuickStartExample.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://graph.facebook.com/v2.8/act_1773889422939937/campaigns
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:207)
	... 12 more
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://graph.facebook.com/v2.8/act_1773889422939937/campaigns
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.facebook.ads.sdk.APIRequest.readResponse(APIRequest.java:205)
	... 12 more
```

**Comment by youminglei** [comment]
I also have this problem, how can I solve it? thank you!

**Comment by youminglei** [comment]
I also have this problem, how can I solve it? thank you! SDK version 3.0.3
